### ISSUE TITLE
Migrate Package to Null Safety on pub.dev

### ISSUE THREAD

**Issue by treyi00** [Supercaly/iirjdart#4]
Can you please migrate the package to Null Safety on pub.dev?

**Comment by eric-nextsense** [comment]
using this too, would be nice if it can be migrated

**Comment by eric-nextsense** [comment]
https://github.com/Supercaly/iirjdart null safe version can be found here

**Comment by JulianBissekkou** [comment]
👀

**Comment by Supercaly** [comment]
Finally I've found the time to update this package, you can find the new version on [pub.dev](https://pub.dev/packages/iirjdart). 
It should work, but open a new issue in case you find some bugs.

Sorry for my late response and thanks for your appreciation.🙏🏻😄
